### ISSUE TITLE
Running on a non-FreeBSD host?

### ISSUE THREAD

**Issue by kyptin** [amontalban/freebsd-docker-images#1]
Hello, and thanks for your work on this image. I particularly appreciated the documentation!

Sorry if this is not the best place to ask this, but I'm having difficulty finding information about this. If you know of a better place to ask this, please advise.

My question is, can this image be made to run on a non-FreeBSD host, like Linux or Mac OS X? And for that matter, do you know what it doesn't work on a non-FreeBSD host? (I thought docker was supposed to avoid that kind of compatibility problem.)

Thanks for the help!

**Comment by amontalban** [comment]
Hi Jeff,

Thanks for the comments and don't worry to get in touch.

Regarding running this image FreeBSD will only work on a FreeBSD host since Docker is not a virtualisation platform.

You can run a VM with FreeBSD and then run Docker on top of it: https://wiki.freebsd.org/Docker

Thanks!

**Comment by kyptin** [comment]
Right! I figured that out about docker at some point, and forgot to circle around to this issue I opened. In case you're interested, I wrote about what I learned [here](http://blog.altometrics.com/2016/06/dockers-dirty-little-secret/).

Cheers, and thanks for the response!
